package Config;

use strict;

# GLOBAL CONFIG
our $DEBUG = "no";
our $ANALYSIS_TIMEOUT = 5;
our $MAX_REP_DETECTION = 150;


# PDF STRUCT TESTS coefs
our $ENCRYPTED_PDF = "ENCRYPTED_PDF";
our $EMPTY_PAGES_WITH_ACTIVE_CONTENT = 99;
our $EMPTY_PAGES_CONTENT = 70;
our $OBJECT_COLLISION_PLUS_BAD_XREF = 90;
our $OBJECT_COLLISION = 10;
our $BAD_XREF_OFFSET = 30;
our $TRAILER_NOT_FOUND = 30;
our $BAD_TRAILER = 40;
our $OBFUSCATED_OBJECTS = 40;
our $MALICIOUS_URI = 50;



# OBJECT ANALYSIS TESTS coefs
our $ACTIVE_CONTENT = 40;
our $SHELLCODE = 40;
our $PATTERN_REPETITION = 40;
our $DANGEROUS_PATTERN_HIGH = 90;
our $DANGEROUS_PATTERN_MEDIUM = 40;
our $DANGEROUS_PATTERN_LOW = 20;
our $TIME_EXCEEDED = 20;


# CVEs TESTS
our $CVE_2010_2883_DETECTED = 50;
our $CVE_2010_2883_BAD_FONT_FILE_LENGTH = 40;


our $MALWARE_DETECTION_COEF = 70;

# 
	
1;;
